## 1.0 Unemployment Data Cleaning

1.1 Import Data

In [1]:
import pandas as pd
unemployment = pd.read_csv("../Data/unemployment by month.csv", index_col = 0)
unemployment.head()

,LNS14000036,LNS14000089,LNS14000091,LNS14000093,LNS14024230
observation_date,,,,,
1948-01-01,5.8,3.0,2.0,2.2,2.9
1948-02-01,6.3,3.3,2.5,2.8,3.1
1948-03-01,7.6,2.9,2.7,2.6,3.0
1948-04-01,6.8,3.4,2.9,2.6,3.0
1948-05-01,6.6,3.0,2.6,2.4,3.1

1.2 Rename Columns

In [2]:
unemployment = unemployment.rename(columns = {"observation_date": "date", "LNS14000036": "20-24", "LNS14000089": "25-34", "LNS14000091": "35-44", "LNS14000093": "45-54", "LNS14024230": "55 & Over"})

unemployment.head()

                  20-24  25-34  35-44  45-54  55 & Over
observation_date
1948-01-01          5.8    3.0    2.0    2.2        2.9
1948-02-01          6.3    3.3    2.5    2.8        3.1
1948-03-01          7.6    2.9    2.7    2.6        3.0
1948-04-01          6.8    3.4    2.9    2.6        3.0
1948-05-01          6.6    3.0    2.6    2.4        3.1

In [3]:
# length of dataset
len(unemployment)

937

1.3 Aggregate Data into Quarters

In [4]:
# Dropping all dates before 2004.
unemployment = unemployment[unemployment.index >= "2004-01-01"]


# Making it quarterly so that it matches net worth data. Setting the resample to start of quarter.
unemployment.index = pd.to_datetime(unemployment.index)
unemployment_quarterly = unemployment.resample("QS").mean()

unemployment_quarterly.head(10)

                     20-24     25-34     35-44     45-54  55 & Over
observation_date
2004-01-01        9.666667  5.766667  4.600000  4.000000   3.733333
2004-04-01        9.566667  5.400000  4.433333  3.933333   3.966667
2004-07-01        9.233333  5.366667  4.366667  3.666667   3.633333
2004-10-01        9.200000  5.500000  4.033333  3.700000   3.633333
2005-01-01        9.566667  5.233333  4.066667  3.500000   3.533333
2005-04-01        8.800000  5.166667  3.833333  3.400000   3.300000
2005-07-01        8.500000  5.133333  3.700000  3.466667   3.400000
2005-10-01        8.333333  5.000000  3.866667  3.533333   3.200000
2006-01-01        8.200000  4.866667  3.700000  3.200000   2.866667
2006-04-01        8.033333  4.766667  3.600000  3.233333   3.000000

1.4 Observe and Check for NaNs/errors

In [5]:
# round to 2 decimal places
unemployment_quarterly = unemployment_quarterly.round(2)
unemployment_quarterly.head(10)

                  20-24  25-34  35-44  45-54  55 & Over
observation_date
2004-01-01         9.67   5.77   4.60   4.00       3.73
2004-04-01         9.57   5.40   4.43   3.93       3.97
2004-07-01         9.23   5.37   4.37   3.67       3.63
2004-10-01         9.20   5.50   4.03   3.70       3.63
2005-01-01         9.57   5.23   4.07   3.50       3.53
2005-04-01         8.80   5.17   3.83   3.40       3.30
2005-07-01         8.50   5.13   3.70   3.47       3.40
2005-10-01         8.33   5.00   3.87   3.53       3.20
2006-01-01         8.20   4.87   3.70   3.20       2.87
2006-04-01         8.03   4.77   3.60   3.23       3.00

In [6]:
# check for NaN values
unemployment_quarterly.isna().sum()

20-24        0
25-34        0
35-44        0
45-54        0
55 & Over    0
dtype: int64

1.5 Save and Export Cleaned Data

In [7]:
unemployment_quarterly.to_csv("../Data/unemployment_cleaned.csv")

## 2.0 Net Worth Data Cleaning

2.1 Import Data

In [8]:
net_worth = pd.read_csv("../Data/net worth by quarter.csv", encoding='ISO-8859-1')
net_worth.head()

,observation_date,WFRBL99T999219,WFRBLB50107,WFRBLN09053,WFRBLN40080,WFRBLT01026,WFRBLTP1246
0,1989-07-01,2904281,717835,7765825,7294817,4661504,1757223
1,1989-10-01,2967026,710392,7887797,7439699,4780063,1813037
2,1990-01-01,2951042,733432,7860072,7526506,4747930,1796888
3,1990-04-01,3004228,711986,7946939,7646319,4844782,1840554
4,1990-07-01,2945256,743216,7844610,7716421,4724032,1778776

In [9]:
len(net_worth)

145

2.2 Rename Columns

In [10]:
net_worth.rename(columns={'WFRBLB50107': '0% to 50%'}, inplace=True)
net_worth.rename(columns={'WFRBLN40080': '50% to 90%'}, inplace=True)
net_worth.rename(columns={'WFRBLN09053': '90% to 99%'}, inplace=True)
net_worth.rename(columns={'WFRBL99T999219': '99% to 99.9%'}, inplace=True)
net_worth.rename(columns={'WFRBLTP1246': '99.9% to 100%'}, inplace=True)
net_worth.rename(columns={'WFRBLT01026': '99% to 100%'}, inplace=True)

# drop overlapping 99% to 100% column
net_worth.drop(columns=['99% to 100%'], inplace=True)

2.3 Rename Dates to Quarters (or match 1.3)

In [11]:
net_worth['observation_date'] = pd.to_datetime(net_worth['observation_date'])
net_worth = net_worth[(net_worth['observation_date'].dt.year >= 2004)]

2.4 Observe and Check for NaNs/errors

In [12]:
net_worth.head()

,observation_date,99% to 99.9%,0% to 50%,90% to 99%,50% to 90%,99.9% to 100%
58,2004-01-01,8459950,1271227,18457391,17366467,4998170
59,2004-04-01,8583383,1315495,18747058,17626289,5062727
60,2004-07-01,8829100,1301414,19173523,17927833,5235743
61,2004-10-01,9188232,1339662,20006859,18514915,5581091
62,2005-01-01,9289867,1362075,20368587,18794466,5657173

In [13]:
# check for errors
net_worth.isna().sum()

observation_date    0
99% to 99.9%        0
0% to 50%           0
90% to 99%          0
50% to 90%          0
99.9% to 100%       0
dtype: int64

2.5 Save and Export Cleaned Data

In [14]:
net_worth.to_csv("../Data/net_worth_cleaned.csv", index=False)